apiVersion: v1
kind: Service
metadata:
  name: tms-service
spec:
  selector:
    app: tms
  ports:
    - protocol: TCP
      port: 8084       # Cluster IP service port
      targetPort: 8083 # Container port
  type: NodePort
