apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms-deployment
  labels:
    app: tms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tms
  template:
    metadata:
      labels:
        app: tms
    spec:
      containers:
        - name: springboot-tms-container
          image: sarveshmorey/springboot_tms-app:latest 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-service:3306/task_management?useSSL=false&allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "Sarvesh@01"
